/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.vista;

/**
 *
 * @author Hp
 */
public class frmJuegoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmJuegoPrincipal
     */
    public frmJuegoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        lblPartida = new javax.swing.JLabel();
        pnlSuperior1 = new javax.swing.JPanel();
        lblRonda = new javax.swing.JLabel();
        lblPozo = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        pnlInferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlRondaSig = new javax.swing.JPanel();
        btnSiguienteRonda = new javax.swing.JButton();
        btnSiguientePartida = new javax.swing.JButton();
        mnJuego = new javax.swing.JMenuBar();
        mnPartida = new javax.swing.JMenu();
        mniGuardar = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        mnVer = new javax.swing.JMenu();
        mniEstadisticas = new javax.swing.JMenuItem();
        mniRanking = new javax.swing.JMenuItem();
        mniHistorial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPartida.setText("Partida:");

        lblRonda.setText("Ronda:");

        lblPozo.setText("Pozo acumulado:");

        javax.swing.GroupLayout pnlSuperior1Layout = new javax.swing.GroupLayout(pnlSuperior1);
        pnlSuperior1.setLayout(pnlSuperior1Layout);
        pnlSuperior1Layout.setHorizontalGroup(
            pnlSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperior1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblRonda)
                .addGap(78, 78, 78)
                .addComponent(lblPozo)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        pnlSuperior1Layout.setVerticalGroup(
            pnlSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperior1Layout.createSequentialGroup()
                .addGroup(pnlSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRonda)
                    .addComponent(lblPozo))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPartida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSuperior1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPartida)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Jugador", "Tipo", "Dinero Actual", "Apuesta de Ronda", "Resultado de dados", "Victorias Acumuladas"
            }
        ));
        jScrollPane2.setViewportView(tblDatos);

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSiguienteRonda.setText("Siguiente Ronda");

        btnSiguientePartida.setText("Siguiente Partida");

        javax.swing.GroupLayout pnlRondaSigLayout = new javax.swing.GroupLayout(pnlRondaSig);
        pnlRondaSig.setLayout(pnlRondaSigLayout);
        pnlRondaSigLayout.setHorizontalGroup(
            pnlRondaSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRondaSigLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlRondaSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguienteRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguientePartida))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlRondaSigLayout.setVerticalGroup(
            pnlRondaSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRondaSigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSiguienteRonda)
                .addGap(18, 18, 18)
                .addComponent(btnSiguientePartida)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        mnPartida.setText("Partida");

        mniGuardar.setText("Guardar");
        mnPartida.add(mniGuardar);

        mniSalir.setText("Salir");
        mnPartida.add(mniSalir);

        mnJuego.add(mnPartida);

        mnVer.setText("Ver");

        mniEstadisticas.setText("Estadisticas");
        mniEstadisticas.setName("mnuEstadisticas"); // NOI18N
        mnVer.add(mniEstadisticas);

        mniRanking.setText("Ranking");
        mniRanking.setName("mnuRanking"); // NOI18N
        mnVer.add(mniRanking);

        mniHistorial.setText("Historial");
        mniHistorial.setName("mnuHistorial"); // NOI18N
        mnVer.add(mniHistorial);

        mnJuego.add(mnVer);

        setJMenuBar(mnJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRondaSig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlRondaSig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJuegoPrincipal().setVisible(true);
            }
        });
    }
    
    
    public javax.swing.JButton getBtnSiguienteRonda() {
      return btnSiguienteRonda;
    }
    
    
    public javax.swing.JButton getBtnSiguientePartida() {
      return btnSiguientePartida;
    }

    public javax.swing.JLabel getLblPartida() {
        return lblPartida;
    }

    public javax.swing.JLabel getLblPozo() {
        return lblPozo;
    }

    public javax.swing.JLabel getLblRonda() {
        return lblRonda;
    }

    public javax.swing.JTable getTblDatos() {
     return tblDatos;
    }

    public javax.swing.JTextArea getTxtLog() {
        return txtLog;
    }

// --- Getters para los Items del Menú ---

    public javax.swing.JMenuItem getMniEstadisticas() {
        return mniEstadisticas;
    }

    public javax.swing.JMenuItem getMniGuardar() {
        return mniGuardar;
    }

    public javax.swing.JMenuItem getMniHistorial() {
        return mniHistorial;
    }

    public javax.swing.JMenuItem getMniRanking() {
        return mniRanking;
    }

    public javax.swing.JMenuItem getMniSalir() {
        return mniSalir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguientePartida;
    private javax.swing.JButton btnSiguienteRonda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPartida;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JMenuBar mnJuego;
    private javax.swing.JMenu mnPartida;
    private javax.swing.JMenu mnVer;
    private javax.swing.JMenuItem mniEstadisticas;
    private javax.swing.JMenuItem mniGuardar;
    private javax.swing.JMenuItem mniHistorial;
    private javax.swing.JMenuItem mniRanking;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlRondaSig;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JPanel pnlSuperior1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
